apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-app
  labels:
    app: swiggy-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swiggy-app
  template:
    metadata:
      labels:
        app: swiggy-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: swiggy-app
        image: 512272320701.dkr.ecr.ca-central-1.amazonaws.com/jiggs:6
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
